[package]
edition = "2021"
name = "hmmmm_derive"
description = "Derive macros for the hmmmm crate."
version = "0.1.0"
license = "MIT"

[lib]
name = "hmmmm_derive"
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = {version = "1.0", features = ["derive", "parsing", "extra-traits", "full"]}

[dev-dependencies]
hmmmm = {path = "../hmmmm"}
