[package]
name = "hmmmm"
description = "Performant and easy-to-use hidden Markov models"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
doctest = false

[dependencies]
approx = "0.5.1"
num-traits = "0.2.15"
rand = "0.8.5"
