[package]
name = "hmmmm"
description = "Performant and easy-to-use hidden Markov models"
version = "0.1.2"
edition = "2021"
license = "MIT"
documentation = "https://docs.rs/hmmmm"
homepage = "https://github.com/dangreco/hmmmm"
repository = "https://github.com/dangreco/hmmmm"
authors = ["Dan Greco <dan.greco@live.com>"]
readme = "README.md"
categories = ["mathematics", "science"]
keywords = ["markov", "hmm", "viterbi"]

[lib]
doctest = false

[dependencies]
approx = "0.5.1"
num-traits = "0.2.15"
rand = "0.8.5"
hmmmm_derive = { version = "0.1.0", optional = true, path = "../hmmmm_derive" }

[dev-dependencies]
hmmmm_derive = { version = "0.1.0", path = "../hmmmm_derive" }

[features]
derive = ["hmmmm_derive"]